# complex functions (for FMM)
import numpy as np

def potential_complex(source, target_coords):
    """Returns potential at a target induced by a source, using 
    complex coords.
    
    Arguments
    ---------   
    source: object with coords and q attribute.
    target: complex number, or object with coords attrtibute.
    form:
    φ := q*log(z-z0) where z and z0 are the coordinates of the
    target and source respectively
    """
    if hasattr(target_coords, 'coords'):
        target_coords = target_coords.coords
    return source.q * np.log(target_coords-source.coords)

def grid_direct_sum_complex(grid):
    """Calculates the complex potential generated by all particles in a grid evaluated
    at where all the particles are by direct summation.

    The potential of each of the particles is stored in the phi attribute of 
    the particles.
    """
    grid.clear_all_phi()
    particles = grid.particles
    for i, target in enumerate(particles):
        for source in (particles[:i] + particles[i+1:]):
            target.phi += potential_complex(source, target.coords)

def direct_sum_complex(particles):
    """Calculates the potential for each particle by direct summation.

    φ := q*log(z-z0) where z and z0 are the coordinates of the
    target and source respectively.
    The potential of each of the particles is added to the phi attribute of 
    the particles.

    This can be used for all particles in existance, or just for a subset 
    of particles.
    """
    for i, target in enumerate(particles):
        for source in (particles[:i] + particles[i+1:]):
            target.phi += potential_complex(source, target.coords)

def direct_source_target_complex(sources, targets):
    """Calculates the potential induced by a group of SOURCE particles, 
    evaluated at each of the TARGET particles, using direct summation method.

    The potential evaluated at each of the TARGET particles is stored in the 
    phi attribute of the TARGET particles.

    Interactions within the source group and within the target group are ignored.
    
    Arguments:
    ----------
        sources: list of source particles
        targets: list of target particles (phi attribute will be updated)
    """
    for target in targets:
        for source in sources:
            target.phi += potential_complex(source, target.coords)